version: '3.8'

services:
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/usr/src/app
        ports:
            - '8000:8000'
        depends_on:
            - pgdb
    
    pgdb:
        image: postgres
        container_name: pgdb
        hostname: ${DB_HOST}
        environment: 
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5432:5432"
        restart: unless-stopped

  